In [1]:
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784',version=1)

In [2]:
x = mnist['data']
y = mnist['target']

In [5]:
x_train = x[:60000]
x_test = x[60000:]
y_train = y[:60000]
y_test = y[60000:]
y_train_5 = (y_train == '5')
y_test_5 = (y_test == '5')

In [7]:
from sklearn.model_selection import cross_val_score
from sklearn.base import BaseEstimator
import numpy as np
import pandas as pd
class Never5Classifier(BaseEstimator):
    def fit(self,x,y =None):
        pass
    def predict (self,x):
        return np.zeros((len(x),1),dtype = bool)
never_5_clf = Never5Classifier()
cross_val_score(never_5_clf,x_train,y_train_5,cv=3,scoring="accuracy")

array([0.91125, 0.90855, 0.90915])

In [8]:
from sklearn.linear_model import SGDClassifier
sgd_clf = SGDClassifier(tol=None,max_iter=5,random_state=42)
sgd_clf.fit(x_train,y_train_5)

SGDClassifier(max_iter=5, random_state=42, tol=None)

In [9]:
from sklearn.model_selection import cross_val_predict

y_train_pred = cross_val_predict(sgd_clf,x_train,y_train_5,cv=3)

In [12]:
y_train_pred

array([ True, False, False, ...,  True, False,  True])

In [13]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_train_5,y_train_pred)

array([[52336,  2243],
       [ 1060,  4361]], dtype=int64)

In [14]:
from sklearn.metrics import precision_score,recall_score
precision_score(y_train_5,y_train_pred)

0.6603573591762568

In [15]:
recall_score(y_train_5,y_train_pred)

0.8044641210108836

In [16]:
from sklearn.metrics import f1_score
f1_score(y_train_5,y_train_pred)

0.7253222453222454