In [1]:
from sklearn import svm
X = [[0,0],[1,1]]
y = [0,1]
clf = svm.SVC()


In [2]:
clf.fit(X,y)

SVC()

In [3]:
clf.predict([[2., 2.]])

array([1])

In [4]:
####################################

In [5]:
from sklearn import svm
X = [[1,2],[2,3],[3,4],[2,1],[3,2],[4,3]]
y = [-1, -1, -1, 1, 1, 1]
clf1 = svm.SVC()

In [6]:
clf1.fit(X,y)

SVC()

In [7]:
clf1.predict([[2, 2]])

array([1])

In [8]:
clf1.predict([[1.5, 1.5]])

array([-1])

In [9]:
clf.support_vectors_

array([[0., 0.],
       [1., 1.]])

In [10]:
clf1.support_vectors_

array([[1., 2.],
       [2., 3.],
       [3., 4.],
       [2., 1.],
       [3., 2.],
       [4., 3.]])

In [11]:
###########################################

In [12]:
from sklearn import svm
X = [[1,2],[2,3],[3,4],[7,1],[2,1],[3,2],[4,3],[1,8]]
y = [-1, -1, -1,1, 1, 1, 1,-1]
clf3 = svm.SVC()

In [13]:
clf3.fit(X,y)

SVC()

In [14]:
clf3.support_vectors_

array([[1., 2.],
       [2., 3.],
       [3., 4.],
       [1., 8.],
       [7., 1.],
       [2., 1.],
       [3., 2.],
       [4., 3.]])

In [15]:
clf.support_

array([0, 1])

In [16]:
clf.n_support_

array([1, 1])

In [17]:
#####################################

In [18]:
X = [[0],[1],[2],[3]]
Y = [0, 1, 2, 3]
clf5=svm.SVC(decision_function_shape='ovo')
clf5.fit(X,Y)

SVC(decision_function_shape='ovo')

In [19]:
# 4 classes: 4*3/2 = 6
dec = clf5.decision_function([[1]])
dec.shape[1]

6

In [20]:
clf5.decision_function_shape="ovr"
dec = clf5.decision_function([[1]])
dec.shape[1]  # 4 classes

4

In [21]:
lin_clf = svm.LinearSVC()
lin_clf.fit(X,Y)

LinearSVC()

In [22]:
dec = lin_clf.decision_function([[1]])
dec.shape[1]

4

In [23]:
###########################################

In [24]:
from sklearn import svm
X = [[0,0],[2,2]]
y = [0.5, 2.5]
regr = svm.SVR()
regr.fit(X,y)

SVR()

In [25]:
regr.predict([[1,1]])

array([1.5])

In [26]:
#########################################

In [27]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
clf6 = make_pipeline(StandardScaler(),SVC())

In [28]:
linear_svc = svm.SVC(kernel='linear')
linear_svc.kernel

'linear'

In [29]:
rbf_svc = svm.SVC(kernel='rbf')
rbf_svc.kernel

'rbf'

In [30]:
import numpy as np
from sklearn import svm
def my_kernel(X,Y):
    return np.dot(X,Y.T)

clf7 = svm.SVC(kernel=my_kernel)

In [31]:
import numpy as np
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn import svm
X, y =make_classification(n_samples=10, random_state=0)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
clf8 = svm.SVC(kernel='precomputed')

In [32]:
# linear kernel computation
gram_train = np.dot(X_train, X_train.T)
clf8.fit(gram_train, y_train)

SVC(kernel='precomputed')

In [34]:
gram_test = np.dot(X_test, X_train.T)
clf8.predict(gram_test)

array([0, 1, 0])