In [2]:
import numpy as np

def MaxMinNormalizaiton(x,Max,Min):
    x =(x-Min)/(Max-Min)
    return  x;

al = np.array([1,2,3,4,5,6])
print(MaxMinNormalizaiton(al,6,1))

[0.  0.2 0.4 0.6 0.8 1. ]


In [ ]:
al = np.array([1,2,3,4,5,6])
print(MaxMinNormalizaiton(al,3,0))

In [4]:
a = np.array([[1,2,3],[4,5,6]])
print(MaxMinNormalizaiton(a,6,1))

[[0.  0.2 0.4]
 [0.6 0.8 1. ]]


In [6]:
al = np.array([[1,2,3,4,5,6],[1,2,3,4,5,6]])
print(MaxMinNormalizaiton(al,6,1))

[[0.  0.2 0.4 0.6 0.8 1. ]
 [0.  0.2 0.4 0.6 0.8 1. ]]


In [7]:
def Z_scoreNormalization(x,m,sigm):
    x= (x-m)/sigm;
    return x;
b = np.array([[1,2,3,4,5,6]])
print(Z_scoreNormalization(b,b.mean(),b.std()))

[[-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]]


In [8]:
b1 = np.array([[1,2,3],[4,5,6]])
print(Z_scoreNormalization(b1,b1.mean(),b1.std()))

[[-1.46385011 -0.87831007 -0.29277002]
 [ 0.29277002  0.87831007  1.46385011]]


In [10]:
def sigmoid(x,usestatus):
    if usestatus:
        return 1.0/(1+np.exp(-x))
    else:
        return float(x)
c = np.array([[1,2,3,4,5,6]])
print(sigmoid(c,1))

[[0.73105858 0.88079708 0.95257413 0.98201379 0.99330715 0.99752738]]


In [12]:
c1 = np.array([[1,2,3],[4,5,6]])
print(sigmoid(c1,1))

[[0.73105858 0.88079708 0.95257413]
 [0.98201379 0.99330715 0.99752738]]
