In [4]:
import numpy as np
from sklearn import preprocessing

x22 = np.array([[1,2,3,4,5,6]])
s22 = preprocessing.MinMaxScaler().fit_transform(x22)
s22

array([[0., 0., 0., 0., 0., 0.]])

In [19]:
from sklearn.preprocessing import MinMaxScaler
s = np.array([[1,2,3,4,5,6]],dtype= 'float64').reshape(-1,1)
scaler = MinMaxScaler(feature_range=(0,1))
scaled = scaler.fit_transform(s)
print(scaled,"\n=========================")
inv_s = scaler.inverse_transform(scaled)
print(inv_s)

[[0. ]
 [0.2]
 [0.4]
 [0.6]
 [0.8]
 [1. ]] 
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]
 [6.]]


In [12]:
import numpy as np
x_np = np.array([1,2,3,4,5,6],dtype='float64')
x_np = x_np.reshape(-1,1)


mean = np.mean(x_np,axis=0)
std = np.std(x_np,axis=0)
print(x_np,"\n=============\n",mean,"\n================\n",std,"\n================")

another_trans_data = x_np-mean
another_trans_data = another_trans_data/std

print(another_trans_data)

[[1.]
 [2.]
 [3.]
 [4.]
 [5.]
 [6.]] 
 [3.5] 
 [1.70782513] 

[[-1.46385011]
 [-0.87831007]
 [-0.29277002]
 [ 0.29277002]
 [ 0.87831007]
 [ 1.46385011]]


In [14]:
import numpy as np
x_np = np.array([[1,2,3,4,5,6],[6,5,4,3,2,1]],dtype='float64')
x_np = x_np.reshape(-1,1)


mean = np.mean(x_np,axis=0)
std = np.std(x_np,axis=0)
print(x_np,"\n=============\n",mean,"\n================\n",std,"\n=============")

another_trans_data = x_np-mean
another_trans_data = another_trans_data/std

print(another_trans_data)

[[1.]
 [2.]
 [3.]
 [4.]
 [5.]
 [6.]
 [6.]
 [5.]
 [4.]
 [3.]
 [2.]
 [1.]] 
 [3.5] 
 [1.70782513] 
[[-1.46385011]
 [-0.87831007]
 [-0.29277002]
 [ 0.29277002]
 [ 0.87831007]
 [ 1.46385011]
 [ 1.46385011]
 [ 0.87831007]
 [ 0.29277002]
 [-0.29277002]
 [-0.87831007]
 [-1.46385011]]


In [17]:
from sklearn.preprocessing import StandardScaler
import numpy as np
x_np = np.array([[1,2,3,4,5,6]])
x_np =x_np.reshape(-1,1)
scaler = StandardScaler()
x_tran = scaler.fit_transform(x_np)
print(x_np,"\n=========\n",scaler.mean_,"\n===========\n",scaler.var_,"\n===========\n",x_tran)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]] 
 [3.5] 
 [2.91666667] 
 [[-1.46385011]
 [-0.87831007]
 [-0.29277002]
 [ 0.29277002]
 [ 0.87831007]
 [ 1.46385011]]
