In [34]:
import numpy as np

a = np.array([[1,2],[3,4]])
# b = np.array([a,[1]])
print(a.shape)
print(a[None,:]) # output: (1, 3, 2)
# print(b)
print(a[:,None].shape) # output: (3, 1, 2)
print(a[:,None,:,None]) # output: (3, 1, 2, 1)
print(a[:,None,None, :]) # output: (3, 1, 1, 2)

# print(a[:,None,:,:])

(2, 2)
[[[1 2]
  [3 4]]]
(2, 1, 2)
[[[[1]
   [2]]]


 [[[3]
   [4]]]]
[[[[1 2]]]


 [[[3 4]]]]


In [15]:
print(a)

[[0.47045784 0.819213  ]]
